# Generated by Django 3.0.4 on 2020-03-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('taken', 'Taken'), ('closed', 'Closed')], default='open', max_length=25),
        ),
    ]
