# Generated by Django 3.0.4 on 2020-03-30 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0003_auto_20200330_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_value',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
