YES_NO_QUESTION = 0
UNIQUE_OPTION_QUESTION = 1
MULTIPLE_OPTION_QUESTION = 2

QUESTION_TYPE =(
    (YES_NO_QUESTION, "Yes/No Question"),
    (UNIQUE_OPTION_QUESTION, "Unique Option Question"),
    (MULTIPLE_OPTION_QUESTION, "Multiple Option Question")
)
